#!/bin/bash

# =====================================
# = please submit improvements to me: =
# = Markus Rathgeb                    =
# = maggu2810@gentooforum.de          =
# =====================================

if [ "$1" != "udev" ]
then
	echo 'add the following lines to your udev rules:
	ACTION=="add"   , KERNEL=="sd[a-z][0-9]", RUN+="/usr/sbin/clenf-am udev %d"
	ACTION=="remove", KERNEL=="sd[a-z][0-9]", RUN+="/usr/sbin/clenf-am udev %d"
	'
	exit 0
fi

TMPDIR="/tmp/automount"
LOGFILE="${TMPDIR}/log"
SDEVNAME="${DEVNAME//\//_}"		# contains an simple name for the device
EDEVFILE="${TMPDIR}/${SDEVNAME}"		# file with the environment by adding the device
MOUNTDIR="/media"

CSETUP="/sbin/cryptsetup"
MAPDIR="/dev/mapper"
VOLID="/sbin/vol_id"

# mount options for all file systems
OPT="rw,noexec,nosuid,nodev"

# -------------------
# ensure that LANG and LC_ALL is set
if [ -e /etc/profile.env ] ; then
	$(grep -e \ LANG -e \ LC_ /etc/profile.env)
fi
# -------------------

mkdir -p ${TMPDIR} ${MOUNTDIR}

# -------------------------
# -- IF DEVICE WAS ADDED --
# -------------------------
if [ "$ACTION" = "add" ]
then

# --------------------------------------------
# -- PREPARE THE DEVICE AND THE ENVIRONMENT --
# --------------------------------------------
	env > ${EDEVFILE}
	case "$ID_FS_TYPE" in
		crypto_LUKS)
			TMPDEVNAME="${MAPDIR}/${SDEVNAME}"
			openvt -s -w -- bash -c "export TERM=linux; clear; ${CSETUP} luksOpen ${DEVNAME} ${SDEVNAME}"
			;;
	    	*)
			TMPDEVNAME="${DEVNAME}"
			;;
	esac
	echo "MY_DEVNAME=${TMPDEVNAME}" >> ${EDEVFILE}
	${VOLID} --export ${TMPDEVNAME} | xargs -I° echo MY_° >> ${EDEVFILE}
	# -- FIND A NAME FOR THE MOUNT DIRECTORY
		TMPLABEL=$($VOLID --label ${TMPDEVNAME})
		if [ "$TMPLABEL" = "" ]
		then
			$TMPLABEL=${SDEVNAME}
		fi
		CNT=""
		MY_MOUNT_DIR="${MOUNTDIR}/${TMPLABEL}"
		while [ -e ${MY_MOUNT_DIR}${CNT} ]
		do
			grep "^${MY_MOUNT_DIR}${CNT} " /etc/mtab &> /dev/null
			if [ $? -eq 1 ]
			then
				rmdir ${MY_MOUNT_DIR}${CNT} &> /dev/null
				if [ $? -eq 0 ]
				then
					break
				fi
			fi
			CNT=$((CNT+1))
		done
		echo "MY_MOUNT_DIR=${MY_MOUNT_DIR}${CNT}" >> ${EDEVFILE}
	# --
	source ${EDEVFILE}

# --------------------------------------------------
# -- MOUNT THE DEVICE                             --
# -- WE SHOULD ONLY USE VARIABLES WITH MY_ PREFIX --
# --------------------------------------------------

	mkdir -p ${MY_MOUNT_DIR}
	case "$MY_ID_FS_TYPE" in
		ext[23])
			mount -o ${OPT} ${MY_DEVNAME} ${MY_MOUNT_DIR}
			;;
		ntfs)
			mount -t ntfs-3g -o ${OPT},allow_other,force ${MY_DEVNAME} ${MY_MOUNT_DIR}
			;;
		vfat)
			mount -t vfat -o ${OPT},umask=0000,dmask=0000,fmask=0000 ${MY_DEVNAME} ${MY_MOUNT_DIR}
			;;
		*)
			rmdir ${MY_MOUNT_DIR}
			;;
	esac

# ---------------------------
# -- IF DEVICE WAS REMOVED --
# ---------------------------
elif [ "$ACTION" = "remove" ]
then
	source ${EDEVFILE}
	umount ${MY_MOUNT_DIR}
	if [ $? -eq 1 ]
	then
		umount -l ${MY_MOUNT_DIR}
	fi
	rmdir ${MY_MOUNT_DIR}
	case "$ID_FS_TYPE" in
		crypto_LUKS)
			$CSETUP luksClose ${SDEVNAME}
			;;
	    	*)
			echo ""
			;;
	esac
	rm ${EDEVFILE}
fi
