#!/bin/bash

resume_skip {
		while [ $? == 1 ]; do emerge --resume --skipfirst; done
}

rebuild_packages() {
	# list of packages that must be rebuild after kernel update
	ALL_REBUILD_PACKAGES="
		app-emulation/virtualbox-modules
		app-emulation/vmware-modules
		net-dialup/slmodem
		net-misc/cisco-vpnclient-3des
		sys-fs/fuse
		x11-base/x11-drm
		x11-drivers/ati-drivers
	"

	# look for ebuilds that are installed and so that must be reuild
	MY_REBUILD=$(for PACKAGE in ${ALL_REBUILD_PACKAGES}; do eix -n -c --only-names -I -A ${PACKAGE}; done)

	# rebuild the installed # == REBUILD KERNEL MODULES ==
	emerge -va1 ${MY_REBUILD}
	resume_skip
}

portage_sync() {
	## === LAYMAN ===
	layman -L &> /dev/null

	OVERLAYS="`for i in $(layman -l |cut -d \  -f 2 | tr -d [:cntrl:] | sed 's/\[39;49;00m/ /g'); do echo $i; done`"

	#layman --sync-all
	for i in $OVERLAYS
	do
		#layman -d $i
		#rm -rf /usr/portage/local/layman/$i
		#layman -a $i
		echo "layman: start updating portage overlay: $i"
		layman -s $i 1>> /tmp/update-layman_1.log 2>> /tmp/update-layman_2.log
		echo "layman: done"
		echo "-"
	done 

	## === MAIN PORTAGE TREE ===
	#eix-sync -v
	emerge --sync
	update-eix
}

handle_elog() {
	# have a look at the elog files
	DATE="$(date +%F_-_%H-%M-%S)"
	TAR="/var/log/portage/${DATE}.tar"
	TMP="$(mktemp --tmpdir=/tmp ${DATE}.XXXXXXXXXX)"
	for FILE in /var/log/portage/elog/*
	do
		echo -e "\n\n==== ${FILE} ===\n" >> ${TMP}
		cat ${FILE} >> ${TMP}
		tar rvf ${TAR} ${FILE}
		rm ${FILE}
	done
	tar rvf ${TAR} ${TMP}
	less ${TMP}
}

revdep_rebuild() {
		rm -f /root/.revdep-rebuild*
		SEARCH_DIRS_MASK="/usr/lib/gcc/i686-pc-linux-uclibc" revdep-rebuild
		rm -f /root/.revdep-rebuild*
}

uworldskip() {
	for i in 1 2; do
		emerge -DNu world
		resume_skip
		revdep_rebuild
		resume_skip
	done

}

## == REBUILD 9999 ==
#emerge -va1 `equery -q -C list -i | grep -E -- -9999 | xargs -I° echo =°`


while [ -n ${1} ]
do
	case "${1}" in
		"--uworldskip")
			uworldskip
			handle_elog
			dispatch-conf
			;;
		"--new-kernel")
			rebuild_packages
			;;
		"--show")
			emerge -vpDNu world
			echo "press return to continue"
			read
			;;
		"--sync")
			portage_sync
			;;
		*)
			echo "unknow command"
			exit 1
		;;
	esac
	shift
done
