# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI="2"

MY_P="${PN}-r${PV}"
MY_PP="${MY_P}-linux-x86"

DESCRIPTION="Open Handset Alliance's Android NDK"
HOMEPAGE="http://developer.android.com/sdk/ndk/${PV/_p/_r}/index.html"
SRC_URI="http://dl.google.com/android/ndk/${MY_PP}.tar.bz2"
RESTRICT="mirror strip"

LICENSE="android"
SLOT="0"
KEYWORDS="~x86 ~amd64"
IUSE="doc"

DEPEND="app-arch/unzip dev-util/android-sdk-update-manager"
RDEPEND=""

QA_TEXTRELS="opt/${P}/platforms/android-3/arch-arm/usr/lib/libc.so
opt/${P}/platforms/android-5/arch-arm/usr/lib/libc.so
opt/${P}/platforms/android-8/arch-arm/usr/lib/libc.so
opt/${P}/platforms/android-3/arch-arm/usr/lib/libdl.so
opt/${P}/platforms/android-8/arch-arm/usr/lib/libdl.so
opt/${P}/platforms/android-3/arch-arm/usr/lib/libthread_db.so"

QA_EXECSTACK=`while read LINE; do echo "opt/${P}/${LINE}"; done <<EOF
platforms/android-9/arch-arm/usr/lib/crtbegin_so.o
platforms/android-9/arch-arm/usr/lib/crtend_so.o
platforms/android-3/arch-arm/usr/lib/crtend_android.o
platforms/android-3/arch-arm/usr/lib/libstdc++.a:one_time_construction.o
platforms/android-3/arch-arm/usr/lib/libstdc++.a:new.o
platforms/android-3/arch-arm/usr/lib/libstdc++.a:pure_virtual.o
platforms/android-3/arch-arm/usr/lib/libstdc++.a:typeinfo.o
platforms/android-3/arch-arm/usr/lib/libthread_db.a:libthread_db.o
platforms/android-3/arch-arm/usr/lib/libc.a:_exit.o
platforms/android-3/arch-arm/usr/lib/libc.a:_exit_thread.o
platforms/android-3/arch-arm/usr/lib/libc.a:__fork.o
platforms/android-3/arch-arm/usr/lib/libc.a:waitid.o
platforms/android-3/arch-arm/usr/lib/libc.a:__clone.o
platforms/android-3/arch-arm/usr/lib/libc.a:execve.o
platforms/android-3/arch-arm/usr/lib/libc.a:setuid.o
platforms/android-3/arch-arm/usr/lib/libc.a:getuid.o
platforms/android-3/arch-arm/usr/lib/libc.a:getgid.o
platforms/android-3/arch-arm/usr/lib/libc.a:geteuid.o
platforms/android-3/arch-arm/usr/lib/libc.a:getegid.o
platforms/android-3/arch-arm/usr/lib/libc.a:getresuid.o
platforms/android-3/arch-arm/usr/lib/libc.a:getresgid.o
platforms/android-3/arch-arm/usr/lib/libc.a:gettid.o
platforms/android-3/arch-arm/usr/lib/libc.a:getgroups.o
platforms/android-3/arch-arm/usr/lib/libc.a:getpgid.o
platforms/android-3/arch-arm/usr/lib/libc.a:getppid.o
platforms/android-3/arch-arm/usr/lib/libc.a:setsid.o
platforms/android-3/arch-arm/usr/lib/libc.a:setgid.o
platforms/android-3/arch-arm/usr/lib/libc.a:setreuid.o
platforms/android-3/arch-arm/usr/lib/libc.a:setresuid.o
platforms/android-3/arch-arm/usr/lib/libc.a:setresgid.o
platforms/android-3/arch-arm/usr/lib/libc.a:__brk.o
platforms/android-3/arch-arm/usr/lib/libc.a:__ptrace.o
platforms/android-3/arch-arm/usr/lib/libc.a:__getpriority.o
platforms/android-3/arch-arm/usr/lib/libc.a:setpriority.o
platforms/android-3/arch-arm/usr/lib/libc.a:setrlimit.o
platforms/android-3/arch-arm/usr/lib/libc.a:getrlimit.o
platforms/android-3/arch-arm/usr/lib/libc.a:getrusage.o
platforms/android-3/arch-arm/usr/lib/libc.a:setgroups.o
platforms/android-3/arch-arm/usr/lib/libc.a:setpgid.o
platforms/android-3/arch-arm/usr/lib/libc.a:vfork.o
platforms/android-3/arch-arm/usr/lib/libc.a:setregid.o
platforms/android-3/arch-arm/usr/lib/libc.a:chroot.o
platforms/android-3/arch-arm/usr/lib/libc.a:prctl.o
platforms/android-3/arch-arm/usr/lib/libc.a:capget.o
platforms/android-3/arch-arm/usr/lib/libc.a:capset.o
platforms/android-3/arch-arm/usr/lib/libc.a:acct.o
platforms/android-3/arch-arm/usr/lib/libc.a:read.o
platforms/android-3/arch-arm/usr/lib/libc.a:write.o
platforms/android-3/arch-arm/usr/lib/libc.a:__pread64.o
platforms/android-3/arch-arm/usr/lib/libc.a:__pwrite64.o
platforms/android-3/arch-arm/usr/lib/libc.a:__open.o
platforms/android-3/arch-arm/usr/lib/libc.a:__openat.o
platforms/android-3/arch-arm/usr/lib/libc.a:close.o
platforms/android-3/arch-arm/usr/lib/libc.a:lseek.o
platforms/android-3/arch-arm/usr/lib/libc.a:__llseek.o
platforms/android-3/arch-arm/usr/lib/libc.a:getpid.o
platforms/android-3/arch-arm/usr/lib/libc.a:__mmap2.o
platforms/android-3/arch-arm/usr/lib/libc.a:munmap.o
platforms/android-3/arch-arm/usr/lib/libc.a:mremap.o
platforms/android-3/arch-arm/usr/lib/libc.a:msync.o
platforms/android-3/arch-arm/usr/lib/libc.a:mprotect.o
platforms/android-3/arch-arm/usr/lib/libc.a:madvise.o
platforms/android-3/arch-arm/usr/lib/libc.a:mlock.o
platforms/android-3/arch-arm/usr/lib/libc.a:munlock.o
platforms/android-3/arch-arm/usr/lib/libc.a:mincore.o
platforms/android-3/arch-arm/usr/lib/libc.a:__ioctl.o
platforms/android-3/arch-arm/usr/lib/libc.a:readv.o
platforms/android-3/arch-arm/usr/lib/libc.a:writev.o
platforms/android-3/arch-arm/usr/lib/libc.a:__fcntl.o
platforms/android-3/arch-arm/usr/lib/libc.a:flock.o
platforms/android-3/arch-arm/usr/lib/libc.a:fchmod.o
platforms/android-3/arch-arm/usr/lib/libc.a:dup.o
platforms/android-3/arch-arm/usr/lib/libc.a:pipe.o
platforms/android-3/arch-arm/usr/lib/libc.a:dup2.o
platforms/android-3/arch-arm/usr/lib/libc.a:select.o
platforms/android-3/arch-arm/usr/lib/libc.a:ftruncate.o
platforms/android-3/arch-arm/usr/lib/libc.a:getdents.o
platforms/android-3/arch-arm/usr/lib/libc.a:fsync.o
platforms/android-3/arch-arm/usr/lib/libc.a:fchown.o
platforms/android-3/arch-arm/usr/lib/libc.a:sync.o
platforms/android-3/arch-arm/usr/lib/libc.a:__fcntl64.o
platforms/android-3/arch-arm/usr/lib/libc.a:fstatfs.o
platforms/android-3/arch-arm/usr/lib/libc.a:sendfile.o
platforms/android-3/arch-arm/usr/lib/libc.a:fstatat.o
platforms/android-3/arch-arm/usr/lib/libc.a:mkdirat.o
platforms/android-3/arch-arm/usr/lib/libc.a:fchownat.o
platforms/android-3/arch-arm/usr/lib/libc.a:fchmodat.o
platforms/android-3/arch-arm/usr/lib/libc.a:renameat.o
platforms/android-3/arch-arm/usr/lib/libc.a:link.o
platforms/android-3/arch-arm/usr/lib/libc.a:unlink.o
platforms/android-3/arch-arm/usr/lib/libc.a:unlinkat.o
platforms/android-3/arch-arm/usr/lib/libc.a:chdir.o
platforms/android-3/arch-arm/usr/lib/libc.a:mknod.o
platforms/android-3/arch-arm/usr/lib/libc.a:chmod.o
platforms/android-3/arch-arm/usr/lib/libc.a:chown.o
platforms/android-3/arch-arm/usr/lib/libc.a:lchown.o
platforms/android-3/arch-arm/usr/lib/libc.a:mount.o
platforms/android-3/arch-arm/usr/lib/libc.a:umount2.o
platforms/android-3/arch-arm/usr/lib/libc.a:fstat.o
platforms/android-3/arch-arm/usr/lib/libc.a:stat.o
platforms/android-3/arch-arm/usr/lib/libc.a:lstat.o
platforms/android-3/arch-arm/usr/lib/libc.a:mkdir.o
platforms/android-3/arch-arm/usr/lib/libc.a:readlink.o
platforms/android-3/arch-arm/usr/lib/libc.a:rmdir.o
platforms/android-3/arch-arm/usr/lib/libc.a:rename.o
platforms/android-3/arch-arm/usr/lib/libc.a:__getcwd.o
platforms/android-3/arch-arm/usr/lib/libc.a:access.o
platforms/android-3/arch-arm/usr/lib/libc.a:symlink.o
platforms/android-3/arch-arm/usr/lib/libc.a:fchdir.o
platforms/android-3/arch-arm/usr/lib/libc.a:truncate.o
platforms/android-3/arch-arm/usr/lib/libc.a:__statfs64.o
platforms/android-3/arch-arm/usr/lib/libc.a:pause.o
platforms/android-3/arch-arm/usr/lib/libc.a:gettimeofday.o
platforms/android-3/arch-arm/usr/lib/libc.a:settimeofday.o
platforms/android-3/arch-arm/usr/lib/libc.a:times.o
platforms/android-3/arch-arm/usr/lib/libc.a:nanosleep.o
platforms/android-3/arch-arm/usr/lib/libc.a:clock_gettime.o
platforms/android-3/arch-arm/usr/lib/libc.a:clock_settime.o
platforms/android-3/arch-arm/usr/lib/libc.a:clock_getres.o
platforms/android-3/arch-arm/usr/lib/libc.a:clock_nanosleep.o
platforms/android-3/arch-arm/usr/lib/libc.a:getitimer.o
platforms/android-3/arch-arm/usr/lib/libc.a:setitimer.o
platforms/android-3/arch-arm/usr/lib/libc.a:__timer_create.o
platforms/android-3/arch-arm/usr/lib/libc.a:__timer_settime.o
platforms/android-3/arch-arm/usr/lib/libc.a:__timer_gettime.o
platforms/android-3/arch-arm/usr/lib/libc.a:__timer_getoverrun.o
platforms/android-3/arch-arm/usr/lib/libc.a:__timer_delete.o
platforms/android-3/arch-arm/usr/lib/libc.a:utimes.o
platforms/android-3/arch-arm/usr/lib/libc.a:sigaction.o
platforms/android-3/arch-arm/usr/lib/libc.a:sigprocmask.o
platforms/android-3/arch-arm/usr/lib/libc.a:__sigsuspend.o
platforms/android-3/arch-arm/usr/lib/libc.a:__rt_sigaction.o
platforms/android-3/arch-arm/usr/lib/libc.a:__rt_sigprocmask.o
platforms/android-3/arch-arm/usr/lib/libc.a:__rt_sigtimedwait.o
platforms/android-3/arch-arm/usr/lib/libc.a:sigpending.o
platforms/android-3/arch-arm/usr/lib/libc.a:socket.o
platforms/android-3/arch-arm/usr/lib/libc.a:socketpair.o
platforms/android-3/arch-arm/usr/lib/libc.a:bind.o
platforms/android-3/arch-arm/usr/lib/libc.a:connect.o
platforms/android-3/arch-arm/usr/lib/libc.a:listen.o
platforms/android-3/arch-arm/usr/lib/libc.a:accept.o
platforms/android-3/arch-arm/usr/lib/libc.a:getsockname.o
platforms/android-3/arch-arm/usr/lib/libc.a:getpeername.o
platforms/android-3/arch-arm/usr/lib/libc.a:sendto.o
platforms/android-3/arch-arm/usr/lib/libc.a:recvfrom.o
platforms/android-3/arch-arm/usr/lib/libc.a:shutdown.o
platforms/android-3/arch-arm/usr/lib/libc.a:setsockopt.o
platforms/android-3/arch-arm/usr/lib/libc.a:getsockopt.o
platforms/android-3/arch-arm/usr/lib/libc.a:sendmsg.o
platforms/android-3/arch-arm/usr/lib/libc.a:recvmsg.o
platforms/android-3/arch-arm/usr/lib/libc.a:sched_setscheduler.o
platforms/android-3/arch-arm/usr/lib/libc.a:sched_getscheduler.o
platforms/android-3/arch-arm/usr/lib/libc.a:sched_yield.o
platforms/android-3/arch-arm/usr/lib/libc.a:sched_setparam.o
platforms/android-3/arch-arm/usr/lib/libc.a:sched_getparam.o
platforms/android-3/arch-arm/usr/lib/libc.a:sched_get_priority_max.o
platforms/android-3/arch-arm/usr/lib/libc.a:sched_get_priority_min.o
platforms/android-3/arch-arm/usr/lib/libc.a:sched_rr_get_interval.o
platforms/android-3/arch-arm/usr/lib/libc.a:uname.o
platforms/android-3/arch-arm/usr/lib/libc.a:__wait4.o
platforms/android-3/arch-arm/usr/lib/libc.a:umask.o
platforms/android-3/arch-arm/usr/lib/libc.a:__reboot.o
platforms/android-3/arch-arm/usr/lib/libc.a:__syslog.o
platforms/android-3/arch-arm/usr/lib/libc.a:init_module.o
platforms/android-3/arch-arm/usr/lib/libc.a:delete_module.o
platforms/android-3/arch-arm/usr/lib/libc.a:klogctl.o
platforms/android-3/arch-arm/usr/lib/libc.a:futex.o
platforms/android-3/arch-arm/usr/lib/libc.a:epoll_create.o
platforms/android-3/arch-arm/usr/lib/libc.a:epoll_ctl.o
platforms/android-3/arch-arm/usr/lib/libc.a:epoll_wait.o
platforms/android-3/arch-arm/usr/lib/libc.a:inotify_init.o
platforms/android-3/arch-arm/usr/lib/libc.a:inotify_add_watch.o
platforms/android-3/arch-arm/usr/lib/libc.a:inotify_rm_watch.o
platforms/android-3/arch-arm/usr/lib/libc.a:poll.o
platforms/android-3/arch-arm/usr/lib/libc.a:__set_tls.o
platforms/android-3/arch-arm/usr/lib/libc.a:cacheflush.o
platforms/android-3/arch-arm/usr/lib/libc.a:__get_pc.o
platforms/android-3/arch-arm/usr/lib/libc.a:__get_sp.o
platforms/android-3/arch-arm/usr/lib/libc.a:_exit_with_stack_teardown.o
platforms/android-3/arch-arm/usr/lib/libc.a:_setjmp.o
platforms/android-3/arch-arm/usr/lib/libc.a:atomics_arm.o
platforms/android-3/arch-arm/usr/lib/libc.a:clone.o
platforms/android-3/arch-arm/usr/lib/libc.a:ffs.o
platforms/android-3/arch-arm/usr/lib/libc.a:kill.o
platforms/android-3/arch-arm/usr/lib/libc.a:tkill.o
platforms/android-3/arch-arm/usr/lib/libc.a:memcmp.o
platforms/android-3/arch-arm/usr/lib/libc.a:memcmp16.o
platforms/android-3/arch-arm/usr/lib/libc.a:memcpy.o
platforms/android-3/arch-arm/usr/lib/libc.a:memset.o
platforms/android-3/arch-arm/usr/lib/libc.a:setjmp.o
platforms/android-3/arch-arm/usr/lib/libc.a:sigsetjmp.o
platforms/android-3/arch-arm/usr/lib/libc.a:syscall.o
platforms/android-3/arch-arm/usr/lib/libc.a:memmove.o
platforms/android-3/arch-arm/usr/lib/libc.a:res_state.o
platforms/android-3/arch-arm/usr/lib/libc.a:strlen.o
platforms/android-3/arch-arm/usr/lib/libc.a:pthread.o
platforms/android-3/arch-arm/usr/lib/libc.a:pthread-timers.o
platforms/android-3/arch-arm/usr/lib/libc.a:ptrace.o
platforms/android-3/arch-arm/usr/lib/libc.a:abort.o
platforms/android-3/arch-arm/usr/lib/libc.a:alarm.o
platforms/android-3/arch-arm/usr/lib/libc.a:brk.o
platforms/android-3/arch-arm/usr/lib/libc.a:creat.o
platforms/android-3/arch-arm/usr/lib/libc.a:daemon.o
platforms/android-3/arch-arm/usr/lib/libc.a:exec.o
platforms/android-3/arch-arm/usr/lib/libc.a:fcntl.o
platforms/android-3/arch-arm/usr/lib/libc.a:fnmatch.o
platforms/android-3/arch-arm/usr/lib/libc.a:ftime.o
platforms/android-3/arch-arm/usr/lib/libc.a:ftok.o
platforms/android-3/arch-arm/usr/lib/libc.a:getcwd.o
platforms/android-3/arch-arm/usr/lib/libc.a:getdtablesize.o
platforms/android-3/arch-arm/usr/lib/libc.a:gethostname.o
platforms/android-3/arch-arm/usr/lib/libc.a:getopt_long.o
platforms/android-3/arch-arm/usr/lib/libc.a:getpgrp.o
platforms/android-3/arch-arm/usr/lib/libc.a:getpriority.o
platforms/android-3/arch-arm/usr/lib/libc.a:getpt.o
platforms/android-3/arch-arm/usr/lib/libc.a:initgroups.o
platforms/android-3/arch-arm/usr/lib/libc.a:isatty.o
platforms/android-3/arch-arm/usr/lib/libc.a:issetugid.o
platforms/android-3/arch-arm/usr/lib/libc.a:lseek64.o
platforms/android-3/arch-arm/usr/lib/libc.a:mmap.o
platforms/android-3/arch-arm/usr/lib/libc.a:nice.o
platforms/android-3/arch-arm/usr/lib/libc.a:open.o
platforms/android-3/arch-arm/usr/lib/libc.a:openat.o
platforms/android-3/arch-arm/usr/lib/libc.a:opendir.o
platforms/android-3/arch-arm/usr/lib/libc.a:pathconf.o
platforms/android-3/arch-arm/usr/lib/libc.a:perror.o
platforms/android-3/arch-arm/usr/lib/libc.a:popen.o
platforms/android-3/arch-arm/usr/lib/libc.a:pread.o
platforms/android-3/arch-arm/usr/lib/libc.a:pselect.o
platforms/android-3/arch-arm/usr/lib/libc.a:ptsname.o
platforms/android-3/arch-arm/usr/lib/libc.a:ptsname_r.o
platforms/android-3/arch-arm/usr/lib/libc.a:pwrite.o
platforms/android-3/arch-arm/usr/lib/libc.a:raise.o
platforms/android-3/arch-arm/usr/lib/libc.a:reboot.o
platforms/android-3/arch-arm/usr/lib/libc.a:recv.o
platforms/android-3/arch-arm/usr/lib/libc.a:sbrk.o
platforms/android-3/arch-arm/usr/lib/libc.a:send.o
platforms/android-3/arch-arm/usr/lib/libc.a:setegid.o
platforms/android-3/arch-arm/usr/lib/libc.a:seteuid.o
platforms/android-3/arch-arm/usr/lib/libc.a:setpgrp.o
platforms/android-3/arch-arm/usr/lib/libc.a:sigblock.o
platforms/android-3/arch-arm/usr/lib/libc.a:siginterrupt.o
platforms/android-3/arch-arm/usr/lib/libc.a:siglist.o
platforms/android-3/arch-arm/usr/lib/libc.a:signal.o
platforms/android-3/arch-arm/usr/lib/libc.a:sigsetmask.o
platforms/android-3/arch-arm/usr/lib/libc.a:sigsuspend.o
platforms/android-3/arch-arm/usr/lib/libc.a:sigwait.o
platforms/android-3/arch-arm/usr/lib/libc.a:sleep.o
platforms/android-3/arch-arm/usr/lib/libc.a:statfs.o
platforms/android-3/arch-arm/usr/lib/libc.a:strsignal.o
platforms/android-3/arch-arm/usr/lib/libc.a:sysconf.o
platforms/android-3/arch-arm/usr/lib/libc.a:syslog.o
platforms/android-3/arch-arm/usr/lib/libc.a:system.o
platforms/android-3/arch-arm/usr/lib/libc.a:tcgetpgrp.o
platforms/android-3/arch-arm/usr/lib/libc.a:tcsetpgrp.o
platforms/android-3/arch-arm/usr/lib/libc.a:time.o
platforms/android-3/arch-arm/usr/lib/libc.a:umount.o
platforms/android-3/arch-arm/usr/lib/libc.a:unlockpt.o
platforms/android-3/arch-arm/usr/lib/libc.a:usleep.o
platforms/android-3/arch-arm/usr/lib/libc.a:wait.o
platforms/android-3/arch-arm/usr/lib/libc.a:asprintf.o
platforms/android-3/arch-arm/usr/lib/libc.a:clrerr.o
platforms/android-3/arch-arm/usr/lib/libc.a:fclose.o
platforms/android-3/arch-arm/usr/lib/libc.a:fdopen.o
platforms/android-3/arch-arm/usr/lib/libc.a:feof.o
platforms/android-3/arch-arm/usr/lib/libc.a:ferror.o
platforms/android-3/arch-arm/usr/lib/libc.a:fflush.o
platforms/android-3/arch-arm/usr/lib/libc.a:fgetc.o
platforms/android-3/arch-arm/usr/lib/libc.a:fgetln.o
platforms/android-3/arch-arm/usr/lib/libc.a:fgetpos.o
platforms/android-3/arch-arm/usr/lib/libc.a:fgets.o
platforms/android-3/arch-arm/usr/lib/libc.a:fileno.o
platforms/android-3/arch-arm/usr/lib/libc.a:findfp.o
platforms/android-3/arch-arm/usr/lib/libc.a:flags.o
platforms/android-3/arch-arm/usr/lib/libc.a:flockfile.o
platforms/android-3/arch-arm/usr/lib/libc.a:fopen.o
platforms/android-3/arch-arm/usr/lib/libc.a:fprintf.o
platforms/android-3/arch-arm/usr/lib/libc.a:fpurge.o
platforms/android-3/arch-arm/usr/lib/libc.a:fputc.o
platforms/android-3/arch-arm/usr/lib/libc.a:fputs.o
platforms/android-3/arch-arm/usr/lib/libc.a:fread.o
platforms/android-3/arch-arm/usr/lib/libc.a:freopen.o
platforms/android-3/arch-arm/usr/lib/libc.a:fscanf.o
platforms/android-3/arch-arm/usr/lib/libc.a:fseek.o
platforms/android-3/arch-arm/usr/lib/libc.a:fsetpos.o
platforms/android-3/arch-arm/usr/lib/libc.a:ftell.o
platforms/android-3/arch-arm/usr/lib/libc.a:funopen.o
platforms/android-3/arch-arm/usr/lib/libc.a:fvwrite.o
platforms/android-3/arch-arm/usr/lib/libc.a:fwalk.o
platforms/android-3/arch-arm/usr/lib/libc.a:fwrite.o
platforms/android-3/arch-arm/usr/lib/libc.a:getc.o
platforms/android-3/arch-arm/usr/lib/libc.a:getchar.o
platforms/android-3/arch-arm/usr/lib/libc.a:gets.o
platforms/android-3/arch-arm/usr/lib/libc.a:makebuf.o
platforms/android-3/arch-arm/usr/lib/libc.a:mktemp.o
platforms/android-3/arch-arm/usr/lib/libc.a:printf.o
platforms/android-3/arch-arm/usr/lib/libc.a:putc.o
platforms/android-3/arch-arm/usr/lib/libc.a:putchar.o
platforms/android-3/arch-arm/usr/lib/libc.a:puts.o
platforms/android-3/arch-arm/usr/lib/libc.a:putw.o
platforms/android-3/arch-arm/usr/lib/libc.a:refill.o
platforms/android-3/arch-arm/usr/lib/libc.a:remove.o
platforms/android-3/arch-arm/usr/lib/libc.a:rewind.o
platforms/android-3/arch-arm/usr/lib/libc.a:rget.o
platforms/android-3/arch-arm/usr/lib/libc.a:scanf.o
platforms/android-3/arch-arm/usr/lib/libc.a:setbuf.o
platforms/android-3/arch-arm/usr/lib/libc.a:setbuffer.o
platforms/android-3/arch-arm/usr/lib/libc.a:setvbuf.o
platforms/android-3/arch-arm/usr/lib/libc.a:snprintf.o
platforms/android-3/arch-arm/usr/lib/libc.a:sprintf.o
platforms/android-3/arch-arm/usr/lib/libc.a:sscanf.o
platforms/android-3/arch-arm/usr/lib/libc.a:stdio.o
platforms/android-3/arch-arm/usr/lib/libc.a:tempnam.o
platforms/android-3/arch-arm/usr/lib/libc.a:tmpfile.o
platforms/android-3/arch-arm/usr/lib/libc.a:tmpnam.o
platforms/android-3/arch-arm/usr/lib/libc.a:ungetc.o
platforms/android-3/arch-arm/usr/lib/libc.a:vasprintf.o
platforms/android-3/arch-arm/usr/lib/libc.a:vfprintf.o
platforms/android-3/arch-arm/usr/lib/libc.a:vfscanf.o
platforms/android-3/arch-arm/usr/lib/libc.a:vprintf.o
platforms/android-3/arch-arm/usr/lib/libc.a:vsnprintf.o
platforms/android-3/arch-arm/usr/lib/libc.a:vsprintf.o
platforms/android-3/arch-arm/usr/lib/libc.a:vscanf.o
platforms/android-3/arch-arm/usr/lib/libc.a:vsscanf.o
platforms/android-3/arch-arm/usr/lib/libc.a:wbuf.o
platforms/android-3/arch-arm/usr/lib/libc.a:wsetup.o
platforms/android-3/arch-arm/usr/lib/libc.a:_rand48.o
platforms/android-3/arch-arm/usr/lib/libc.a:assert.o
platforms/android-3/arch-arm/usr/lib/libc.a:atexit.o
platforms/android-3/arch-arm/usr/lib/libc.a:atoi.o
platforms/android-3/arch-arm/usr/lib/libc.a:atol.o
platforms/android-3/arch-arm/usr/lib/libc.a:atoll.o
platforms/android-3/arch-arm/usr/lib/libc.a:bsearch.o
platforms/android-3/arch-arm/usr/lib/libc.a:ctype_.o
platforms/android-3/arch-arm/usr/lib/libc.a:div.o
platforms/android-3/arch-arm/usr/lib/libc.a:exit.o
platforms/android-3/arch-arm/usr/lib/libc.a:getenv.o
platforms/android-3/arch-arm/usr/lib/libc.a:jrand48.o
platforms/android-3/arch-arm/usr/lib/libc.a:ldiv.o
platforms/android-3/arch-arm/usr/lib/libc.a:lldiv.o
platforms/android-3/arch-arm/usr/lib/libc.a:locale.o
platforms/android-3/arch-arm/usr/lib/libc.a:lrand48.o
platforms/android-3/arch-arm/usr/lib/libc.a:mrand48.o
platforms/android-3/arch-arm/usr/lib/libc.a:nrand48.o
platforms/android-3/arch-arm/usr/lib/libc.a:putenv.o
platforms/android-3/arch-arm/usr/lib/libc.a:qsort.o
platforms/android-3/arch-arm/usr/lib/libc.a:seed48.o
platforms/android-3/arch-arm/usr/lib/libc.a:setenv.o
platforms/android-3/arch-arm/usr/lib/libc.a:setjmperr.o
platforms/android-3/arch-arm/usr/lib/libc.a:srand48.o
platforms/android-3/arch-arm/usr/lib/libc.a:strntoimax.o
platforms/android-3/arch-arm/usr/lib/libc.a:strntoumax.o
platforms/android-3/arch-arm/usr/lib/libc.a:strtod.o
platforms/android-3/arch-arm/usr/lib/libc.a:strtoimax.o
platforms/android-3/arch-arm/usr/lib/libc.a:strtol.o
platforms/android-3/arch-arm/usr/lib/libc.a:strtoll.o
platforms/android-3/arch-arm/usr/lib/libc.a:strtoul.o
platforms/android-3/arch-arm/usr/lib/libc.a:strtoull.o
platforms/android-3/arch-arm/usr/lib/libc.a:strtoumax.o
platforms/android-3/arch-arm/usr/lib/libc.a:tolower_.o
platforms/android-3/arch-arm/usr/lib/libc.a:toupper_.o
platforms/android-3/arch-arm/usr/lib/libc.a:wchar.o
platforms/android-3/arch-arm/usr/lib/libc.a:bcopy.o
platforms/android-3/arch-arm/usr/lib/libc.a:index.o
platforms/android-3/arch-arm/usr/lib/libc.a:memccpy.o
platforms/android-3/arch-arm/usr/lib/libc.a:memchr.o
platforms/android-3/arch-arm/usr/lib/libc.a:memmem.o
platforms/android-3/arch-arm/usr/lib/libc.a:memrchr.o
platforms/android-3/arch-arm/usr/lib/libc.a:memswap.o
platforms/android-3/arch-arm/usr/lib/libc.a:strcasecmp.o
platforms/android-3/arch-arm/usr/lib/libc.a:strcasestr.o
platforms/android-3/arch-arm/usr/lib/libc.a:strcat.o
platforms/android-3/arch-arm/usr/lib/libc.a:strchr.o
platforms/android-3/arch-arm/usr/lib/libc.a:strcmp.o
platforms/android-3/arch-arm/usr/lib/libc.a:strcoll.o
platforms/android-3/arch-arm/usr/lib/libc.a:strcpy.o
platforms/android-3/arch-arm/usr/lib/libc.a:strcspn.o
platforms/android-3/arch-arm/usr/lib/libc.a:strdup.o
platforms/android-3/arch-arm/usr/lib/libc.a:strerror.o
platforms/android-3/arch-arm/usr/lib/libc.a:strerror_r.o
platforms/android-3/arch-arm/usr/lib/libc.a:strlcat.o
platforms/android-3/arch-arm/usr/lib/libc.a:strlcpy.o
platforms/android-3/arch-arm/usr/lib/libc.a:strncat.o
platforms/android-3/arch-arm/usr/lib/libc.a:strncmp.o
platforms/android-3/arch-arm/usr/lib/libc.a:strncpy.o
platforms/android-3/arch-arm/usr/lib/libc.a:strndup.o
platforms/android-3/arch-arm/usr/lib/libc.a:strnlen.o
platforms/android-3/arch-arm/usr/lib/libc.a:strpbrk.o
platforms/android-3/arch-arm/usr/lib/libc.a:strrchr.o
platforms/android-3/arch-arm/usr/lib/libc.a:strsep.o
platforms/android-3/arch-arm/usr/lib/libc.a:strspn.o
platforms/android-3/arch-arm/usr/lib/libc.a:strstr.o
platforms/android-3/arch-arm/usr/lib/libc.a:strtok.o
platforms/android-3/arch-arm/usr/lib/libc.a:strtotimeval.o
platforms/android-3/arch-arm/usr/lib/libc.a:strxfrm.o
platforms/android-3/arch-arm/usr/lib/libc.a:bindresvport.o
platforms/android-3/arch-arm/usr/lib/libc.a:inet_addr.o
platforms/android-3/arch-arm/usr/lib/libc.a:inet_aton.o
platforms/android-3/arch-arm/usr/lib/libc.a:inet_ntoa.o
platforms/android-3/arch-arm/usr/lib/libc.a:inet_ntop.o
platforms/android-3/arch-arm/usr/lib/libc.a:inet_pton.o
platforms/android-3/arch-arm/usr/lib/libc.a:asctime.o
platforms/android-3/arch-arm/usr/lib/libc.a:difftime.o
platforms/android-3/arch-arm/usr/lib/libc.a:localtime.o
platforms/android-3/arch-arm/usr/lib/libc.a:strftime.o
platforms/android-3/arch-arm/usr/lib/libc.a:strptime.o
platforms/android-3/arch-arm/usr/lib/libc.a:__errno.o
platforms/android-3/arch-arm/usr/lib/libc.a:__set_errno.o
platforms/android-3/arch-arm/usr/lib/libc.a:_rand48.o
platforms/android-3/arch-arm/usr/lib/libc.a:arc4random.o
platforms/android-3/arch-arm/usr/lib/libc.a:basename.o
platforms/android-3/arch-arm/usr/lib/libc.a:basename_r.o
platforms/android-3/arch-arm/usr/lib/libc.a:dirname.o
platforms/android-3/arch-arm/usr/lib/libc.a:dirname_r.o
platforms/android-3/arch-arm/usr/lib/libc.a:drand48.o
platforms/android-3/arch-arm/usr/lib/libc.a:erand48.o
platforms/android-3/arch-arm/usr/lib/libc.a:fork.o
platforms/android-3/arch-arm/usr/lib/libc.a:if_nametoindex.o
platforms/android-3/arch-arm/usr/lib/libc.a:if_indextoname.o
platforms/android-3/arch-arm/usr/lib/libc.a:ioctl.o
platforms/android-3/arch-arm/usr/lib/libc.a:ldexp.o
platforms/android-3/arch-arm/usr/lib/libc.a:libc_init_common.o
platforms/android-3/arch-arm/usr/lib/libc.a:logd_write.o
platforms/android-3/arch-arm/usr/lib/libc.a:md5.o
platforms/android-3/arch-arm/usr/lib/libc.a:pututline.o
platforms/android-3/arch-arm/usr/lib/libc.a:realpath.o
platforms/android-3/arch-arm/usr/lib/libc.a:semaphore.o
platforms/android-3/arch-arm/usr/lib/libc.a:sha1.o
platforms/android-3/arch-arm/usr/lib/libc.a:ssp.o
platforms/android-3/arch-arm/usr/lib/libc.a:stubs.o
platforms/android-3/arch-arm/usr/lib/libc.a:system_properties.o
platforms/android-3/arch-arm/usr/lib/libc.a:time64.o
platforms/android-3/arch-arm/usr/lib/libc.a:thread_atexit.o
platforms/android-3/arch-arm/usr/lib/libc.a:utime.o
platforms/android-3/arch-arm/usr/lib/libc.a:utmp.o
platforms/android-3/arch-arm/usr/lib/libc.a:gethnamaddr.o
platforms/android-3/arch-arm/usr/lib/libc.a:ev_timers.o
platforms/android-3/arch-arm/usr/lib/libc.a:ev_streams.o
platforms/android-3/arch-arm/usr/lib/libc.a:nsap_addr.o
platforms/android-3/arch-arm/usr/lib/libc.a:__dn_comp.o
platforms/android-3/arch-arm/usr/lib/libc.a:__res_close.o
platforms/android-3/arch-arm/usr/lib/libc.a:__res_send.o
platforms/android-3/arch-arm/usr/lib/libc.a:herror.o
platforms/android-3/arch-arm/usr/lib/libc.a:res_comp.o
platforms/android-3/arch-arm/usr/lib/libc.a:res_data.o
platforms/android-3/arch-arm/usr/lib/libc.a:res_debug.o
platforms/android-3/arch-arm/usr/lib/libc.a:res_init.o
platforms/android-3/arch-arm/usr/lib/libc.a:res_mkquery.o
platforms/android-3/arch-arm/usr/lib/libc.a:res_query.o
platforms/android-3/arch-arm/usr/lib/libc.a:res_send.o
platforms/android-3/arch-arm/usr/lib/libc.a:res_cache.o
platforms/android-3/arch-arm/usr/lib/libc.a:nsdispatch.o
platforms/android-3/arch-arm/usr/lib/libc.a:getaddrinfo.o
platforms/android-3/arch-arm/usr/lib/libc.a:getnameinfo.o
platforms/android-3/arch-arm/usr/lib/libc.a:getservbyname.o
platforms/android-3/arch-arm/usr/lib/libc.a:getservent.o
platforms/android-3/arch-arm/usr/lib/libc.a:base64.o
platforms/android-3/arch-arm/usr/lib/libc.a:getservbyport.o
platforms/android-3/arch-arm/usr/lib/libc.a:ns_name.o
platforms/android-3/arch-arm/usr/lib/libc.a:ns_parse.o
platforms/android-3/arch-arm/usr/lib/libc.a:ns_ttl.o
platforms/android-3/arch-arm/usr/lib/libc.a:ns_netint.o
platforms/android-3/arch-arm/usr/lib/libc.a:ns_print.o
platforms/android-3/arch-arm/usr/lib/libc.a:ns_samedomain.o
platforms/android-3/arch-arm/usr/lib/libc.a:eabi.o
platforms/android-3/arch-arm/usr/lib/libc.a:socketcalls.o
platforms/android-3/arch-arm/usr/lib/libc.a:dlmalloc.o
platforms/android-3/arch-arm/usr/lib/libc.a:libc_init_static.o
platforms/android-3/arch-arm/usr/lib/libc.a:exidx_static.o
platforms/android-3/arch-arm/usr/lib/libm.a:isinf.o
platforms/android-3/arch-arm/usr/lib/libm.a:fpclassify.o
platforms/android-3/arch-arm/usr/lib/libm.a:b_exp.o
platforms/android-3/arch-arm/usr/lib/libm.a:b_log.o
platforms/android-3/arch-arm/usr/lib/libm.a:b_tgamma.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_acos.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_acosf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_acosh.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_acoshf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_asin.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_asinf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_atan2.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_atan2f.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_atanh.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_atanhf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_cosh.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_coshf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_exp.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_expf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_fmod.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_fmodf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_gamma.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_gamma_r.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_gammaf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_gammaf_r.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_hypot.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_hypotf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_j0.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_j0f.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_j1.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_j1f.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_jn.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_jnf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_lgamma.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_lgamma_r.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_lgammaf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_lgammaf_r.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_log.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_log10.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_log10f.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_logf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_pow.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_powf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_rem_pio2.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_rem_pio2f.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_remainder.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_remainderf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_scalb.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_scalbf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_sinh.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_sinhf.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_sqrt.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_sqrtf.o
platforms/android-3/arch-arm/usr/lib/libm.a:k_cos.o
platforms/android-3/arch-arm/usr/lib/libm.a:k_cosf.o
platforms/android-3/arch-arm/usr/lib/libm.a:k_rem_pio2.o
platforms/android-3/arch-arm/usr/lib/libm.a:k_sin.o
platforms/android-3/arch-arm/usr/lib/libm.a:k_sinf.o
platforms/android-3/arch-arm/usr/lib/libm.a:k_tan.o
platforms/android-3/arch-arm/usr/lib/libm.a:k_tanf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_asinh.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_asinhf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_atan.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_atanf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_cbrt.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_cbrtf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_ceil.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_ceilf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_ceill.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_copysign.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_copysignf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_cos.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_cosf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_erf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_erff.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_exp2.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_exp2f.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_expm1.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_expm1f.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_fabsf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_fdim.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_finite.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_finitef.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_floor.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_floorf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_floorl.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_fma.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_fmaf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_fmax.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_fmaxf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_fmaxl.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_fmin.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_fminf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_fminl.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_frexpf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_ilogb.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_ilogbf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_ilogbl.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_isfinite.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_isnormal.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_llrint.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_llrintf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_llround.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_llroundf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_llroundl.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_log1p.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_log1pf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_logb.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_logbf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_lrint.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_lrintf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_lround.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_lroundf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_lroundl.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_modff.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_nearbyint.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_nextafter.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_nextafterf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_nexttowardf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_remquo.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_remquof.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_rint.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_rintf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_round.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_roundf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_roundl.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_signbit.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_signgam.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_significand.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_significandf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_sin.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_sinf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_tan.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_tanf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_tanh.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_tanhf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_trunc.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_truncf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_truncl.o
platforms/android-3/arch-arm/usr/lib/libm.a:w_drem.o
platforms/android-3/arch-arm/usr/lib/libm.a:w_dremf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_copysignl.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_fabsl.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_fabs.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_frexp.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_isnan.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_modf.o
platforms/android-3/arch-arm/usr/lib/libm.a:fenv.o
platforms/android-3/arch-arm/usr/lib/libm.a:e_ldexpf.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_scalbln.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_scalbn.o
platforms/android-3/arch-arm/usr/lib/libm.a:s_scalbnf.o
platforms/android-3/arch-arm/usr/lib/crtbegin_static.o
platforms/android-3/arch-arm/usr/lib/crtbegin_dynamic.o
toolchains/arm-linux-androideabi-4.4.3/prebuilt/gdbserver
toolchains/arm-eabi-4.4.0/prebuilt/gdbserver
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/crtn.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_udivsi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_divsi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_umodsi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_modsi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_dvmd_tls.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_bb_init_func.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_call_via_rX.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_interwork_call_via_rX.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_lshrdi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_ashrdi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_ashldi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_negdf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_addsubdf3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_muldivdf3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_cmpdf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_unorddf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_fixdfsi.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_fixunsdfsi.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_truncdfsf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_negsf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_addsubsf3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_muldivsf3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_cmpsf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_unordsf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_fixsfsi.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_fixunssfsi.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_floatdidf.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_floatdisf.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_floatundidf.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_arm_floatundisf.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_clzsi2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_clzdi2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_muldi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_aeabi_lcmp.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_aeabi_ulcmp.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_aeabi_ldivmod.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:_aeabi_uldivmod.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/libgcc.a:libunwind.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/crtn.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_udivsi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_divsi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_umodsi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_modsi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_dvmd_tls.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_bb_init_func.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_call_via_rX.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_interwork_call_via_rX.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_lshrdi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_ashrdi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_ashldi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_negdf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_addsubdf3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_muldivdf3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_cmpdf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_unorddf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_fixdfsi.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_fixunsdfsi.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_truncdfsf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_negsf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_addsubsf3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_muldivsf3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_cmpsf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_unordsf2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_fixsfsi.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_fixunssfsi.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_floatdidf.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_floatdisf.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_floatundidf.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_arm_floatundisf.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_clzsi2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_clzdi2.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_muldi3.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_aeabi_lcmp.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_aeabi_ulcmp.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_aeabi_ldivmod.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:_aeabi_uldivmod.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/libgcc.a:libunwind.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/thumb/crti.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/lib/gcc/arm-eabi/4.4.0/crti.o
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/libexec/gcc/arm-eabi/4.4.0/cc1plus
toolchains/arm-eabi-4.4.0/prebuilt/linux-x86/libexec/gcc/arm-eabi/4.4.0/cc1
EOF`

src_install(){
	local destdir="/opt/${P/_p*/}"
	dodir "${destdir}"

	cd "${MY_P}"
	cp -pPR GNUmakefile build platforms toolchains samples sources tests ndk-build ndk-gdb "${D}/${destdir}/" || die "failed to copy"
	#mkdir "${D}/${destdir}/out" || die "failed to create out dir"
	#chgrp android "${D}/${destdir}/samples" || die "failed to chgrp samples dir"
	#chmod g+w,+t "${D}/${destdir}/samples" || die "failed to chmod samples dir"
	#chgrp android "${D}/${destdir}/out" || die "failed to chgrp out dir"
	#chmod g+ws "${D}/${destdir}/out" || die "failed to chmod out dir" 
	dodoc *.{TXT,html}
	if [ use doc ]; then
		docinto "docs"
		dodoc docs/*.{html,HTML}
		docinto "docs/system/libc"
		dodoc docs/system/libc/*
		docinto "docs/opensles"
		dodoc docs/opensles/*
	fi

	ewarn "You also have to install the necessary SDK using 'android' command from dev-util/android-sdk-update-manager."
}
